name: Windows dist

inputs:
  arch:
    type: string
    required: true

runs:
  using: 'composite'
  steps:

  - name: install zip command
    uses: crazy-max/ghaction-chocolatey@v2
    with:
      args: install zip

  - name: nmake dist
    shell: cmd
    run: |
      call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" ${{ inputs.arch }}
      cd msvc10
      nmake NODEBUG=1 DIST_NAME=libiconv-${{ github.ref_name }}-windows-${{ inputs.arch}} dist

  - name: list zip
    shell: cmd
    run: dir msvc10\*.zip

  - name: release
    uses: softprops/action-gh-release@v1
    with:
      draft: true
      prerelease: ${{ contains(github.ref_name, '-alpha.') || contains(github.ref_name, '-beta.') }}
      files: |
        msvc10/*.zip
      fail_on_unmatched_files: true
      generate_release_notes: false
      append_body: true
