name: Windows

on: [push]

jobs:

  build:
    runs-on: windows-2022
    defaults:
      run:
        shell: cmd

    steps:

    - uses: actions/checkout@v3

    - name: nmake build
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        cd msvc10
        nmake NODEBUG=1 build

    - name: nmake check
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        cd msvc10
        nmake NODEBUG=1 check

  dist:
    needs: build
    runs-on: windows-2022
    defaults:
      run:
        shell: cmd

    steps:

    - uses: actions/checkout@v3

    - name: install zip command
      uses: crazy-max/ghaction-chocolatey@v2
      with:
        args: install zip

    - name: nmake dist
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        cd msvc10
        nmake NODEBUG=1 dist

    - name: list zip
      run: dir msvc10\*.zip
